from fastapi import FastAPI, UploadFile, File, Form
import fitz
import ollama

app = FastAPI()


@app.get("/")
def home():
    """
    Checks whether the Resume Analyzer backend is running.

    Returns a simple message to confirm that the API is working.
    """
    return {"message": "Resume Analyzer Backend is running!"}


def extract_text_from_pdf(contents):
    """
    Extracts text from an uploaded PDF.

    The function goes through each page of the PDF and
    combines all the extracted text into one string.

    Args:
        contents: The uploaded PDF file contents.

    Returns:
        The complete text extracted from the PDF.
    """
    pdf = fitz.open(stream=contents, filetype="pdf")

    text = ""

    # Go through each page and collect its text.
    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text


@app.post("/upload-resume")
async def upload_resume(
    file: UploadFile = File(...),
    job_description: str | None = Form(None),
    job_description_file: UploadFile | None = File(None)
):
    """
    Uploads a resume and generates an AI-based analysis.

    The function extracts text from the uploaded resume and
    sends it to Qwen3 through Ollama.

    The job description is optional. The user can either
    paste the job description as text or upload it as a PDF.

    If a job description is provided, the AI compares the
    resume with the job description and identifies matching
    and missing skills.

    The analysis also includes an ATS compatibility assessment,
    resume strengths, weaknesses, and suggestions for improvement.

    Args:
        file: The resume PDF uploaded by the user.
        job_description: An optional job description pasted by the user.
        job_description_file: An optional job description uploaded as a PDF.

    Returns:
        The resume filename, extracted resume text, job description,
        and AI-generated analysis.
    """

    # Read the uploaded resume PDF.
    contents = await file.read()

    # Extract text from the resume.
    text = extract_text_from_pdf(contents)

    # Start with the pasted job description, if one was provided.
    final_job_description = job_description

    # If a JD PDF was uploaded, extract its text.
    if job_description_file:
        jd_contents = await job_description_file.read()
        final_job_description = extract_text_from_pdf(jd_contents)

    # Create the basic resume analysis instructions.
    analysis_request = f"""
Analyze this resume and provide:

1. Overall resume score out of 100

2. ATS compatibility assessment
   - Check whether the resume is easy for an ATS to read.
   - Check the use of relevant keywords.
   - Check whether the sections and information are clearly structured.
   - Point out any formatting or content issues that may affect ATS compatibility.

3. Strengths

4. Weaknesses

5. Missing skills or important keywords

6. Suggestions for improvement
"""

    # Add job comparison only when a job description is provided.
    if final_job_description:
        analysis_request += f"""
7. Resume and job description match score out of 100

8. Skills that match the job description

9. Skills missing for the job description

Job Description:
{final_job_description}
"""

    # Add the resume text to the AI prompt.
    analysis_request += f"""

Resume:
{text}
"""

    # Send the resume and analysis instructions to Qwen3.
    response = ollama.chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "user",
                "content": analysis_request
            }
        ]
    )

    # Get the analysis generated by the AI model.
    analysis = response["message"]["content"]

    return {
        "filename": file.filename,
        "text": text,
        "job_description": final_job_description,
        "analysis": analysis
    }