from fastapi import FastAPI, UploadFile, File, Form
import fitz
import ollama

app = FastAPI()


@app.get("/")
def home():
    """
    Checks whether the Resume Analyzer backend is running.

    Returns a simple message to confirm that the API is working.
    """
    return {"message": "Resume Analyzer Backend is running!"}


def extract_text_from_pdf(contents):
    """
    Extracts text from the uploaded PDF.

    The function goes through each page of the PDF and
    combines all the extracted text into one string.

    Args:
        contents: The uploaded PDF file contents.

    Returns:
        The complete text extracted from the PDF.
    """
    pdf = fitz.open(stream=contents, filetype="pdf")

    text = ""

    # Go through each page and collect its text.
    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text


@app.post("/upload-resume")
async def upload_resume(
    file: UploadFile = File(...),
    job_description: str = Form(...)
):
    """
    Uploads a resume and compares it with the given job description.

    The function extracts the text from the resume and sends
    both the resume and job description to Qwen3 through Ollama.

    The AI analysis includes the match score, matching skills,
    missing skills, strengths, and suggestions for improvement.

    Args:
        file: The resume PDF uploaded by the user.
        job_description: The job description entered by the user.

    Returns:
        The resume filename, extracted text, job description,
        and AI-generated analysis.
    """

    # Read the uploaded resume PDF.
    contents = await file.read()

    # Extract text from the resume.
    text = extract_text_from_pdf(contents)

    # Send the resume and job description to Qwen3 for analysis.
    response = ollama.chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "user",
                "content": f"""
Compare this resume with the given job description and provide:

1. Match score out of 100
2. Skills that match the job description
3. Skills missing from the resume
4. Strengths of the resume for this job
5. Areas that need improvement
6. Suggestions to make the resume better suited for this job

Job Description:
{job_description}

Resume:
{text}
"""
            }
        ]
    )

    # Get the analysis generated by the AI model.
    analysis = response["message"]["content"]

    return {
        "filename": file.filename,
        "text": text,
        "job_description": job_description,
        "analysis": analysis
    }