from fastapi import FastAPI, UploadFile, File
import fitz
import ollama

app = FastAPI()


@app.get("/")
def home():
    """Check that the Resume Analyzer backend is running."""
    return {"message": "Resume Analyzer Backend is running!"}


def extract_text_from_pdf(contents):
    """Extract text from all pages of an uploaded PDF."""

    pdf = fitz.open(stream=contents, filetype="pdf")

    text = ""

    # Extract and combine text from each page.
    for page in pdf:
        text += page.get_text()

    pdf.close()

    return text


@app.post("/upload-resume")
async def upload_resume(file: UploadFile = File(...)):
    """
    Upload a resume PDF, extract its text,
    and analyze it using the Qwen3 model.
    """

    # Read the uploaded PDF file.
    contents = await file.read()

    # Extract text from the uploaded resume.
    text = extract_text_from_pdf(contents)

    # Send the extracted resume text to Qwen3 for analysis.
    response = ollama.chat(
        model="qwen3:8b",
        messages=[
            {
                "role": "user",
                "content": f"""
Analyze this resume and provide:
1. Resume score out of 100
2. Strengths
3. Weaknesses
4. Missing skills
5. Suggestions for improvement

Resume:
{text}
"""
            }
        ]
    )

    # Get the analysis generated by the AI model.
    analysis = response["message"]["content"]

    return {
        "filename": file.filename,
        "text": text,
        "analysis": analysis
    }